language: generic

env:
- LUA="lua=5.3"

install:
- sudo apt-get install luarocks
- sudo luarocks install --server=http://luarocks.org/manifests/kikito md5
- sudo luarocks install busted

script: "busted crimp_spec.lua"

notifications:
  email: false