language: python
sudo: false

env:
- LUA="5.1"

before_install:
- pip install hererocks
- hererocks here -l$LUA -r3
- source here/bin/activate

install:
- luarocks install crimp-1.0.0-0.rockspec --only-deps

script: "luarocks test"

notifications:
  email: false